apiVersion: aws.crossplane.io/v1alpha3
kind: Provider
metadata:
  name: aws-provider
spec:
  region: us-central-1
  credentialsSecretRef:
    name: aws-account-creds
    namespace: crossplane-system
    key: credentials
