apiVersion: database.aws.crossplane.io/v1beta1
kind: DBSubnetGroup
metadata:
  name: dbsubnetgroup
spec:
  forProvider:
    description: placeholder_for_description
    subnetIdRefs:
      - name: subnet-a
      - name: subnet-b
      - name: subnet-c
  reclaimPolicy: Delete
  providerRef:
    name: aws-provider
