---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: RouteTable
metadata:
  name: routetable
spec:
  forProvider:
    vpcIdRef:
      name: vpc
    routes:
      - destinationCidrBlock: 0.0.0.0/0
        gatewayIdRef:
          name: internetgateway
    associations:
      - subnetIdRef:
          name: subnet-a
      - subnetIdRef:
          name: subnet-b
      - subnetIdRef:
          name: subnet-c
  reclaimPolicy: Delete
  providerRef:
    name: aws-provider