---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: awssamples.aws.stacks.crossplane.io
spec:
  preserveUnknownFields: true
  group: aws.stacks.crossplane.io
  names:
    kind: AWSSample
    listKind: AWSSampleList
    plural: awssamples
    singular: awssample
  scope: Cluster
  subresources:
    status: {}
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
