---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: minimalaws.aws.resourcepacks.crossplane.io
spec:
  preserveUnknownFields: true
  group: aws.resourcepacks.crossplane.io
  names:
    kind: MinimalAWS
    listKind: MinimalAWSList
    plural: minimalaws
    singular: minimalaws
  scope: Cluster
  subresources:
    status: {}
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
