# permissions to do edit minimalaws.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: minimalaws-editor-role
rules:
- apiGroups:
  - aws.resourcepacks.crossplane.io
  resources:
  - minimalaws
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aws.resourcepacks.crossplane.io
  resources:
  - minimalaws/status
  verbs:
  - get
  - patch
  - update
