# permissions to do viewer minimalaws.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: minimalaws-viewer-role
rules:
- apiGroups:
  - aws.resourcepacks.crossplane.io
  resources:
  - minimalaws
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aws.resourcepacks.crossplane.io
  resources:
  - minimalaws/status
  verbs:
  - get
