apiVersion: network.aws.crossplane.io/v1beta1
kind: InternetGateway
metadata:
  name: internetgateway
spec:
  forProvider:
    vpcIdRef:
      name: vpc
  reclaimPolicy: Delete
  providerRef:
    name: aws-provider
