# should we add security groups for replication group as well?
---
apiVersion: network.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  name: eks-security-group
spec:
  forProvider:
    vpcIdRef:
      name: vpc
    groupName: eks-security-group
    description: Cluster communication with worker nodes
  reclaimPolicy: Delete
  providerRef:
    name: aws-provider
---
apiVersion: network.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  name: rds-security-group
spec:
  forProvider:
    vpcIdRef:
      name: vpc
    groupName: rds-security-group
    description: open rds access to crossplane workload
    ingress:
      - fromPort: 3306
        toPort: 3306
        ipProtocol: tcp
        ipRanges:
          - cidrIp: 0.0.0.0/0
            description: all ips
  reclaimPolicy: Delete
  providerRef:
    name: aws-provider
