---
apiVersion: network.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: vpc
spec:
  forProvider:
    cidrBlock: 192.168.0.0/16
    enableDnsSupport: true
    enableDnsHostNames: true
  reclaimPolicy: Delete
  providerRef:
    name: aws-provider
