title: "AWS Sample Stack"
overviewShort: |
  Configures an AWS environment with basic networking, security, and 
  default resource classes for applications to use.
overview: |
  Configures an AWS environment with basic networking, security,
  and default resource classes that provide a self-service catalog for
  applications to use.
readme: |
  The `AWS Sample Stack` configures the neccesary cloud resources and
  self-service catalog to deploy basic applications like `Wordpress`.

  The managed resources configured by this stack include: `VPC`, `Subnet`,
  `SecurityGroup`, `InternetGateway` `RouteTable`, `IAMRole`, and
  `IAMPolicyAttachment`.

  This stack offers the following resource classes for applications to
  use: `EKSClusterClass`, `RDSInstanceClass`, and a `ReplicationGroupClass`
  for Redis caches.

  The `AWS Sample Stack` also configures a `Provider` connection resource,
  so the `AWS Provider` can communicate with AWS API.

  [Learn More on GitHub](https://github.com/crossplane/stack-aws-sample)
  to see the complete `kustomize` templates used in this stack and as a
  starting point for building your own stack.
maintainers:
- name: "Muvaffak Onus"
  email: "monus@upbound.io"
owners:
- name: "Muvaffak Onus"
  email: "monus@upbound.io"
company: "Crossplane"
category: "Sample Stack"
packageType: "Stack"
keywords:
 - "easy"
 - "aws"
 - "sample"
 - "default"
 - "private network"
website: "https://crossplane.io"
source: "https://github.com/crossplaneio/stack-aws-sample"
permissionScope: Cluster
dependsOn:
  - crd: '*.cache.aws.crossplane.io/v1beta1'
  - crd: '*.compute.aws.crossplane.io/v1alpha3'
  - crd: '*.database.aws.crossplane.io/v1beta1'
  - crd: '*.database.aws.crossplane.io/v1alpha3'
  - crd: '*.identity.aws.crossplane.io/v1alpha3'
  - crd: '*.network.aws.crossplane.io/v1alpha3'
  - crd: '*.aws.crossplane.io/v1alpha3'
  - package: 'crossplane/provider-aws'
# License SPDX name: https://spdx.org/licenses/
license: Apache-2.0
