title: "Stack AWS Sample"
readme: |
  A sample stack with built-in network and classes that let you provision
  resources with minimal node requirements in AWS.
overview: |
  A sample stack with built-in network and classes that let you provision
  resources with minimal node requirements in AWS.
overviewShort: "Sample stack for AWS."
maintainers:
- name: "Muvaffak Onus"
  email: "monus@upbound.io"
owners:
- name: "Muvaffak Onus"
  email: "monus@upbound.io"
company: "Upbound"
category: "Sample Stack"
packageType: "Stack"
keywords:
 - "easy"
 - "aws"
 - "sample"
 - "default"
 - "private network"
website: "upbound.io"
source: "https://github.com/crossplaneio/stack-aws-sample"
permissionScope: Cluster
dependsOn:
  - crd: '*.cache.aws.crossplane.io/v1beta1'
  - crd: '*.compute.aws.crossplane.io/v1alpha3'
  - crd: '*.database.aws.crossplane.io/v1beta1'
  - crd: '*.database.aws.crossplane.io/v1alpha3'
  - crd: '*.identity.aws.crossplane.io/v1alpha3'
  - crd: '*.network.aws.crossplane.io/v1alpha3'
  - crd: '*.aws.crossplane.io/v1alpha3'
  - package: 'crossplane/provider-aws'
# License SPDX name: https://spdx.org/licenses/
license: Apache-2.0
