
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: minimalaws.aws.resourcepacks.crossplane.io
spec:
  group: aws.resourcepacks.crossplane.io
  names:
    kind: MinimalAWS
    plural: minimalaws
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: MinimalAWS is the Schema for the minimalaws API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: MinimalAWSSpec defines the desired state of MinimalAWS
          properties:
            credentialsSecretRef:
              description: CredentialsSecretRef refers to the secret and its key that
                contains the required credentials to connect to AWS.
              properties:
                key:
                  description: The key to select.
                  type: string
                name:
                  description: Name of the secret.
                  type: string
                namespace:
                  description: Namespace of the secret.
                  type: string
              required:
              - key
              - name
              - namespace
              type: object
            region:
              description: Region of the resources that will be deployed.
              type: string
          required:
          - credentialsSecretRef
          - region
          type: object
        status:
          description: MinimalAWSStatus defines the observed state of MinimalAWS
          properties:
            conditions:
              description: Conditions of the resource.
              items:
                description: A Condition that may apply to a managed resource.
                properties:
                  lastTransitionTime:
                    description: LastTransitionTime is the last time this condition
                      transitioned from one status to another.
                    format: date-time
                    type: string
                  message:
                    description: A Message containing details about this condition's
                      last transition from one status to another, if any.
                    type: string
                  reason:
                    description: A Reason for this condition's last transition from
                      one status to another.
                    type: string
                  status:
                    description: Status of this condition; is it currently True, False,
                      or Unknown?
                    type: string
                  type:
                    description: Type of this condition. At most one of each condition
                      type may apply to a resource at any point in time.
                    type: string
                required:
                - lastTransitionTime
                - reason
                - status
                - type
                type: object
              type: array
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
